---
- project:
    templates:
      - network-ee-container-image-jobs
    check:
      jobs: &jobs
        - build-ansible-collection:
            irrelevant-files:
              - tools/cachito/.*
        - network-ee-tox-ansible-builder:
            irrelevant-files:
              - tools/cachito/.*
        - network-ee-build-container-image:
            irrelevant-files:
              - tools/cachito/.*
        - network-ee-build-container-image-stable-2.9:
            irrelevant-files:
              - tools/cachito/.*
        - network-ee-build-container-image-stable-2.10:
            irrelevant-files:
              - tools/cachito/.*
        - network-ee-build-container-image-stable-2.11:
            irrelevant-files:
              - tools/cachito/.*
    gate:
      jobs: *jobs
    post:
      jobs:
        - network-ee-upload-container-image:
            vars:
              upload_container_image_promote: false
        - network-ee-upload-container-image-stable-2.9:
            vars:
              upload_container_image_promote: false
        - network-ee-upload-container-image-stable-2.10:
            vars:
              upload_container_image_promote: false
        - network-ee-upload-container-image-stable-2.11:
            vars:
              upload_container_image_promote: false
    periodic:
      jobs:
        - network-ee-upload-container-image:
            vars:
              upload_container_image_promote: false
        - network-ee-upload-container-image-stable-2.9:
            vars:
              upload_container_image_promote: false
        - network-ee-upload-container-image-stable-2.10:
            vars:
              upload_container_image_promote: false
        - network-ee-upload-container-image-stable-2.11:
            vars:
              upload_container_image_promote: false
