---
- project:
    check:
      jobs:
        - network-ee-build-container-image
    gate:
      jobs:
        - network-ee-build-container-image
    post:
      jobs:
        - network-ee-upload-container-image:
            vars:
              upload_container_image_promote: false
